[package]
name = "dgmark-wasmtime"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
dgmark = { path = "../dgmark" }
wee_alloc = { version = "0.4.5", optional = true }
