[package]
name = "dgmark-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
dgmark = { path = "../dgmark" }
wasm-bindgen = { version = "0.2.78", features = ["serde-serialize"] }
js-sys = "0.3.55"
wee_alloc = { version = "0.4.5", optional = true }
